## KBase UI Configuration
---
# TODO: ensure that this list includes all supported services

# Services represent kbase core services. The key for each service
# is the module name as defined in the services spec file.
# Traditionally arbitrary strings were assigned as these keys, typically
# matching the first path component in the proxy (/services/PATH/) url.
# When switching over module name as the canonical service key, these
# old arbitrary keys were moved into the aliases property. Some services
# do not follow the traditional service definition pattern and therefore
# lack this pattern.
services:
    auth2:
        aliases: ["auth", "Auth"]
        url: "{{ deploy.services.urlBase }}/services/auth"
        cookieName: kbase_session
        name: Authorization Version 2
        coreService: true
        type: rest
        version:
            path: /
            propertyPath: version
            minimum: 0.2.0
        # configure per deploy environment
        providers: null
    awe:
        url: "{{ deploy.services.urlBase }}/services/awe-api"
        name: AWE
    Catalog:
        aliases: ["catalog"]
        url: "{{ deploy.services.urlBase }}/services/catalog"
        name: Catalog
        coreService: true
        type: jsonrpc
        version:
            method: version
            minimum: 2.1.0
    Feeds:
        aliases: ["feeds"]
        url: "{{ deploy.services.urlBase }}/services/feeds"
        name: Feeds
        coreService: true
        type: rest
        version:
            path: /
            propertyPath: version
            minimum: 1.0.1
    Groups:
        aliases: ["groups"]
        url: "{{ deploy.services.urlBase }}/services/groups"
        name: Groups
        coreService: true
        type: rest
        version:
            path: /
            propertyPath: version
            minimum: 0.1.0
    ftp_service:
        aliases: ["ftp"]
        url: "{{ deploy.services.urlBase }}/services/kb-ftp-api/v0"
        root: /data/bulk
        name: Staging Service
    NarrativeMethodStore:
        aliases: ["narrative_method_store"]
        url: "{{ deploy.services.urlBase }}/services/narrative_method_store/rpc"
        image_url: "{{ deploy.services.urlBase }}/services/narrative_method_store/"
        name: Narrative Method Store
        coreService: true
        type: jsonrpc
        version:
            method: ver
            minimum: 0.3.6
    shock:
        url: "{{ deploy.services.urlBase }}/services/shock-api"
        name: Shock
    UserProfile:
        aliases: ["user_profile"]
        url: "{{ deploy.services.urlBase }}/services/user_profile/rpc"
        name: User Profile
        coreService: true
        type: jsonrpc
        version:
            method: ver
            minimum: 0.2.0
    UserAndJobState:
        aliases: ["user_job_state"]
        url: "{{ deploy.services.urlBase }}/services/userandjobstate"
        name: User and Job State
    NarrativeJobService:
        aliases: ["narrative_job_service"]
        url: "{{ deploy.services.urlBase }}/services/njs_wrapper"
        name: Narrative Job Service
    KBaseDataImport:
        aliases: ["data_import_export"]
        url: "{{ deploy.services.urlBase }}/services/data_import_export"
        name: Data Import Export
    KBaseSearchEngine:
        aliases: ["search"]
        url: "{{ deploy.services.urlBase }}/services/searchapi2/legacy"
        name: KBase Search Engine
        coreService: true
        type: jsonrpc
        version:
            method: status
            propertyPath: version
            minimum: 0.1.1
    ServiceWizard:
        aliases: ["service_wizard"]
        url: "{{ deploy.services.urlBase }}/services/service_wizard"
        name: Service Wizard
        coreService: true
        type: jsonrpc
        version:
            method: version
            minimum: 0.4.0
    Workspace:
        aliases: ["workspace"]
        url: "{{ deploy.services.urlBase }}/services/ws"
        name: Workspace
        coreService: true
        type: jsonrpc
        version:
            method: ver
            minimum: 0.8.1
    RelationEngine:
        aliases: []
        url: "{{ deploy.services.urlBase }}/services/relation_engine_api"
        name: Relation Engine
        coreService: true
        type: rest
        version:
            path: /
            semverNotImplemented: true

    # Not services, but useful endpoints
    doc_site:
        url: http://kbase.us
        name: Documentation and Support Site
    narrative:
        url: "{{ deploy.services.urlBase }}"
        name: Narrative User Interface
    # search:
    #     url: https://kbase.us/services/search/
    #     name: Data Search
    staging:
        aliases: ["staging_service"]
        url: "{{ deploy.services.urlBase }}/services/staging_service"
    # Overrides for dynamic services can go here. Use the module name for the
    # key and a config-aware dsclient wrapper can use generic client instead
    # to reach this service.
    # jgi_gateway:
    #      url: '{{ deploy.services.urlBase }}/services/jgi_gateway/rpc'
    # KBaseSearchEngine:
    #     url: '{{deploy.services.urlBase}}/services/searchapi2'
    #     name: Local Search
    # NarrativeService:
    #     url: '{{deploy.services.urlBase}}/services/NarrativeService'
    #     name: 'Narrative Service'
    # DashboardService:
    #     url: '{{deploy.services.urlBase}}/services/DashboardService'
    #     name: 'Dashboard Service'
    # UIService:
    #     url: '{{deploy.services.urlBase}}/services/UIService'
    #     name: 'UI Service'
resources:
    docSite:
        base:
            url: http://kbase.us
    documentation:
        loginHelp:
            url: http://kbase.us/help
        narrativeGuide:
            url: http://kbase.us/narrative-guide
        tutorials:
            url: http://kbase.us/tutorials
        apps:
            url: http://kbase.us/apps
        troubleshooting:
            signin: http://kbase.us/troubleshooting/sign-in
        aboutKbase:
            url: http://kbase.us/what-is-kbase/
    userAccount:
        resetPassword:
            url: http://kbase.us/reset-password
        updateProfile:
            url: https://www.globusid.org/profile
        update_profile:
            url: https://www.globusid.org/profile
        access:
            url: https://gologin.kbase.us/globus-app/account
        signUp:
            url: http://kbase.us/sign-up
    contact:
        url: http://kbase.us/contact-us
        name: Contact KBase
    help:
        url: http://kbase.us/help-board/
        name: KBase Help Board
    status_page: http://kbase.us/internal/status
    submit_jira_ticket: https://atlassian.kbase.us/secure/CreateIssueDetails!init.jspa?pid=10200&issuetype=1&description=#Narrative%
